[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "tracker"
description = "Track events via web interface with zero overhead"
dynamic= ["version"]
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = [""]
authors = [
  { name = "hephaisto" },
]
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "nicegui",
]

[project.urls]
source = "https://github.com/hephaisto/tracker"

[project.scripts]
run-web-ui = "tracker.cmdline:main"

[tool.hatch.version]
source = "vcs"

